[build]
  functions = "netlify-functions"
  publish = "public"

[functions]
  # תיקיית הפונקציות
  directory = "netlify-functions"

[[redirects]]
  # הפניית API לפונקציות
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  # הפניית קבצי תמונות
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[headers]]
  # הגדרות CORS
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  # Cache טוב לתמונות
  for = "/images/*"
  [headers.values]
    Cache-Control = "max-age=31536000, public, immutable"

[dev]
  # הגדרות לפיתוח מקומי
  command = "npm run dev"
  port = 8888
  
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"